title: "αβ"
locale: en-US
description: Bonneville or Bust
timezone: "America/New_York"
date_format: "%b %-d, %Y at %I:%M%P"

strict_front_matter: true

# https://jekyllrb.com/docs/configuration/liquid/
error_mode: strict
strict_variables: true
strict_filters: true

# the base hostname & protocol for your site, e.g. http://example.com
url: https://beta5.org

# the subpath of your site, e.g. /blog
# baseurl: "/"

static_images_base_url: https://beta5.org/photos

mapbox_token: pk.eyJ1IjoiYmxhbG9yIiwiYSI6ImNqbWYxcWY3aTA0Ym4zcHFwY25oZXNram4ifQ.j2IzyVihJU3nzKFvBBBMBQ

## these are included _before_ head-custom.html…
head_scripts:
    ## moving jquery up top so we can reference it
    - https://code.jquery.com/jquery-3.3.1.min.js
    ## lity integration in so-simple theme interferes
    # - https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.js
    # - https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.gallery.min.js

    ## map-util is custom
    - /assets/js/map-util.js

## defining footer_scripts disables the defaults, which we want for jquery
footer_scripts:
    - /assets/js/main.min.js
    - https://use.fontawesome.com/releases/v5.4.0/js/all.js ## ninja upgrade!

## maps to _data/authors.yaml
author: blalor@bravo5.org

# ".html" instead of ":output_ext" causes page permalinks to lose their extension
permalink: /:categories/:year-:month-:day-:title:output_ext

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

theme: jekyll-theme-so-simple

plugins:
    - jekyll-feed
    - jekyll-redirect-from

excerpt_separator: "<!--more-->"

collections:
    trips:
        output: true
